# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('parent_id', models.IntegerField(null=True)),
                ('member_num', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
